save-hackage-creds: false
resolver: lts-20.10

extra-deps:
- 'heist-1.1.1.1'
- 'snap-core-1.0.5.1'
- 'readable-0.3.1'

packages:
- 'digestive-functors/'
- 'digestive-functors-blaze/'
- 'digestive-functors-happstack/'
- 'digestive-functors-heist/'
- 'digestive-functors-snap/'
